import type { Metadata } from "next";
import './css/globals.css';
import ThemeContextProvider from "./providers/ThemeContextProvider";
import { ShoppingCartContextProvider } from "./providers/ShoppingCartProvider";

export const metadata: Metadata = {
  title: "Shoppify",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ShoppingCartContextProvider>
        <ThemeContextProvider>
          <body>
            {children}
          </body>
        </ThemeContextProvider>
      </ShoppingCartContextProvider>
    </html>
  );
}
